name: Update Docker
on:
  schedule:
    - cron:  '0 0 1,15 * *'
jobs:
  build_and_push_image:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: profiq/node-java-chrome-ff:latest
      - name: Get latest chrome version
        run: |
          echo "CHROME_VERSION=$(google-chrome --version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 | sed '/Google Chrome /s///')" >> $GITHUB_ENV
      - name: Push to Docker Hub with chrome version
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: profiq/node-java-chrome-ff:${{ env.CHROME_VERSION }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: profiq/node-java-chrome-ff:latest
    steps:
      - name: Run tests.sh
        run: tests.sh

